coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 5%

ignore:
  - "tests/*"
  - "src/gui/tkinter_fonts.py"
