[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "code-analyser"
version = "0.1.0"
description = "Pluggable AST metrics extractor for Python code analysis"
authors = [
    { name = "Samuel Harrison", email = "sh18784@essex.ac.uk" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
ast-metrics = "metrics.main:main"
